[package]
name = "egui-data-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]

[dependencies]
egui = "0.26"
egui_extras = { version = "0.26", default-features = false }
tap = "1"

[dev-dependencies]
eframe = { version = "0.26", features = ["serde", "persistence"] }
fastrand = "2"
names = { version = "0.14", default-features = false }
