name: Cargo Publish

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        run: cargo publish
        
        