name: Cargo Publish

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
      - run: cargo test
      - run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo install cargo-semver-checks
      - run: cargo semver-checks
      - run: cargo publish
        
        