name: Build and Deploy Demo Web App

on:
  push:
    branches:
      - master
    paths: 
      - 'demo/**'
      - 'examples/**'
      - 'src/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk@^0.20
      - run: trunk build --release --verbose --public-url /egui-data-table ./demo/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./demo/dist"
          
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
